### PR TITLE
Treat WRAP_CONTENT as the largest display dimension.

### PR DESCRIPTION
**Pull request by colinrtwhite**
Fixes: https://github.com/coil-kt/coil/issues/20

### CODE REVIEW

**Comment by mario** [comment]
@colinrtwhite I still experience the issue in #20, even with Master SNAPSHOT.

**Comment by mario** [comment]
(For full transparency, the issue is visible when setting a placeholder)

**Comment by colinrtwhite** [comment]
@mario Could you open a new bug to track (+ a reproduction case if possible)? Thanks!

**Comment by mario** [comment]
Let me try to come up with a self contained sample - if I manage to do it,
will post along with an issue.

Thank you for your your continued patience.

**Comment by colinrtwhite** [comment]
Thanks! No problem, thanks for helping improve Coil.

**Pull request merged**
