### PR TITLE
Generate sample icon

### PR DESCRIPTION
**Pull request by Jawnnypoo**
This creates app icons for the sample project using the Coil logo. 😎 

Screen Shot 2019-08-12 at 10 34 09 AM

### CODE REVIEW

**Comment by colinrtwhite** [comment]
Awesome! Thanks. Can you run the PNGs through a compressor (I'm a fan of `zopfli`) and the vector drawables through [Avocado](https://github.com/alexjlockwood/avocado) if you haven't already?

**Comment by Jawnnypoo** [comment]
All done!

**Comment by colinrtwhite** [comment]
Two more comments:

- Can you rename `ic_launcher_background.xml` -> `colors.xml`.
- We should move `ic_launcher_foreground.xml` to `drawable-v24` so it's not packaged with the app on lower API levels.

Thanks!

**Comment by Jawnnypoo** [comment]
Makes sense, should be good now!

**Pull request merged**
