### PR TITLE
Add unit tests for `Uri.pathSegments` extension

### PR DESCRIPTION
**Pull request by SimonMarquis**
This might require an update after #2027

### CODE REVIEW

**Comment by colinrtwhite** [comment]
Thanks, I just merged https://github.com/coil-kt/coil/pull/2027. Can you update with those changes?

**Comment by SimonMarquis** [comment]
@colinrtwhite this should be good to review now :)

I've taken the liberty to move the test assertion of `skipsEmptyPathSegments` to match the other. Let me know if you prefer the `pathSegments` being asserted last, or directly after the `path`.

**Comment by SimonMarquis** [comment]
Although this currently fails:

- https://github.com/SimonMarquis/coil/blob/2b6afd6e1c8c1cb50e91210e9ec3b340b349a996/coil-core/src/commonTest/kotlin/coil3/UriTest.kt#L56-61
  ```
  Expected :/上海+中國
  Actual   :/%E4%B8%8A%E6%B5%B7%2B%E4%B8%AD%E5%9C%8B
  ```
- https://github.com/SimonMarquis/coil/blob/2b6afd6e1c8c1cb50e91210e9ec3b340b349a996/coil-core/src/commonTest/kotlin/coil3/UriTest.kt#69-74
  ```
  Expected :/上海+中國%6
  Actual   :/%E4%B8%8A%E6%B5%B7%2B%E4%B8%AD%E5%9C%8B%6
  ```
- https://github.com/SimonMarquis/coil/blob/2b6afd6e1c8c1cb50e91210e9ec3b340b349a996/coil-core/src/commonTest/kotlin/coil3/UriTest.kt#L81-L86
  ```
  Expected :[test, image.jpg]
  Actual   :[test, , , image.jpg]
  ```

**Review by colinrtwhite — APPROVED** [review]
Thanks!

**Pull request merged**
