### PR TITLE
Bump AGP to 4.2.0

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Comment by colinrtwhite** [comment]
@Goooler CI is failing due to a change in how `com.vanniktech:gradle-maven-publish-plugin` works. It'd probably be good to address that in a separate PR.

**Comment by kickym0802** [comment]
Colin White ***@***.***> 於 2021年5月6日 週四 01:03 寫道：

**Comment by Goooler** [comment]
> @Goooler CI is failing due to a change in how `com.vanniktech:gradle-maven-publish-plugin` works. It'd probably be good to address that in a separate PR.

You are right, I tried to copy `dokkaHtmlPartialPlugin` from source to solve that, but failed.

**Review by colinrtwhite — APPROVED** [review]
Thanks!

**Pull request merged**
