### PR TITLE
Bump gradle to 7.0

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Comment by colinrtwhite** [comment]
That was fast!

**Review by colinrtwhite — APPROVED** [review]

**Comment by Goooler** [comment]
@colinrtwhite Looks like need to update dokka.

**Comment by colinrtwhite** [comment]
Reported here: https://github.com/Kotlin/dokka/issues/1834

**Comment by Goooler** [comment]
@colinrtwhite   This PR may merge again, it should be compitable with Dokka 1.4

**Pull request merged**
