### PR TITLE
Remove multidex declaration

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Comment by colinrtwhite** [comment]
Why should we remove this?

**Comment by Goooler** [comment]
> Why should we remove this?

I noticed you bump minSdk to 21, multidex should be enabled by default.

**Comment by colinrtwhite** [comment]
Ah I didn't notice this was against the `2.x` branch. I added the changes to the branch thanks, however I'd avoid making PRs against that branch at the moment as it's very in flux/experimental.

**Comment by kickym0802** [comment]
Goooler ***@***.***>於 2021年5月6日 週四，上午3:45寫道：

**Comment by kickym0802** [comment]
Colin White ***@***.***>於 2021年5月6日 週四，下午1:13寫道：

**Pull request closed without merging**
