### PR TITLE
Support fallback drawable when request data is null.

### PR DESCRIPTION
**Pull request by colinrtwhite**
Fixes: #61

### CODE REVIEW

**Comment by spauldhaliwal** [comment]
Looking forward to this!

**Comment by colinrtwhite** [comment]
Merging this in, however its behaviour might change while in master and before the stable `0.9.0` release.

**Comment by bishiboosh** [comment]
@colinrtwhite how does this affect `ImageView.clear` ? This uses `loadAny` with null value and would display an error drawable in the image view instead of just canceling requests

**Comment by colinrtwhite** [comment]
@bishiboosh Yep, currently on master this will trigger the `onError` callback. This will be fixed before the `0.9.0` release as part of https://github.com/coil-kt/coil/pull/179.

**Pull request merged**
